using System;
using System.Collections.Generic;
using System.Linq;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace OpenMagic.Tests
{
    public class RandomNumberTests
    {
        [TestClass]
        public class NextInt
        {
            [TestMethod]
            void ShouldGetRandomNumbers()
            {

                // Given
                var randomNumbers = new List<int>();

                // When
                for (int index = 1; index <= 1000; index++)
                {
                    randomNumbers.Add(RandomNumber.NextInt());
                }

                // Then
                var uniqueNumbers = from i in randomNumbers
                                    group i by i into Group
                                    select new { Number = Group };

                var orderedUniqueNumbers = from i in uniqueNumbers
                                           orderby i
                                           select i;


                Console.WriteLine("{0} unique numbers, out of {1}, generated by random number generator for int.", orderedUniqueNumbers.Count(), randomNumbers.Count());

                uniqueNumbers.Count().Should().BeGreaterThan(1, "because there should be more than 1 random int.");

            }
        }
    }
}
