name: build-and-test

on:
  push:
    # all branches

  pull_request:
    # all branches

env:
  SOLUTION_FILE_PATH: .\OpenMagic.sln
  TESTS_FOLDER: .\tests
  BUILD_CONFIGURATION: Release
  BUILD_TARGET: ReBuild
  BUILD_VERBOSITY: Normal
  PACKAGES_FOLDER: .\packages
  XUNIT_FILE_PATH: .\packages\xunit.runner.console\2.4.2\tools\net472\xunit.console.exe

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out the source code
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}} -PackagesDirectory ${{env.PACKAGES_FOLDER}}

    - name: Debug
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: Get-ChildItem -Recurse
      
    - name: Build OpenMagic solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /maxCpuCount /p:Configuration=${{env.BUILD_CONFIGURATION}} /verbosity:${{env.BUILD_VERBOSITY}} /target:${{env.BUILD_TARGET}} ${{env.SOLUTION_FILE_PATH}} 

    - name: Run unit tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\scripts\run-unit-tests.ps1 -xunitPath ${{env.XUNIT_FILE_PATH}} -testsFolder ${{env.TESTS_FOLDER}} -buildConfiguration ${{env.BUILD_CONFIGURATION}}
