name: build-and-test

on:
  push:
    # all branches

  pull_request:
    # all branches

env:
  PROJECT_NAME: OpenMagic
  SOLUTION_FILE_PATH: .\OpenMagic.sln
  NUGET_FILE_PATH: .\OpenMagic.nuspec
  MAJOR_PROJECT_FOLDER: .\source\OpenMagic
  VERSION: 5.4.0
  TESTS_FOLDER: .\tests
  BUILD_CONFIGURATION: Release
  BUILD_TARGET: ReBuild
  BUILD_VERBOSITY: Normal
  NUGET_SERVER: https://www.myget.org/F/timpmurphy/api/v3/index.json
  PACKAGES_FOLDER: .\packages

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out the source code
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}} -PackagesDirectory ${{env.PACKAGES_FOLDER}}

    - name: Build solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /maxCpuCount /p:Configuration=${{env.BUILD_CONFIGURATION}} /verbosity:${{env.BUILD_VERBOSITY}} /target:${{env.BUILD_TARGET}} ${{env.SOLUTION_FILE_PATH}} 

    - name: Run unit tests
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: dotnet test

    - name: Create artifacts directory
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\scripts\create-artifacts-directory.ps1 -majorProjectFolder ${{env.MAJOR_PROJECT_FOLDER}} -buildConfiguration ${{env.BUILD_CONFIGURATION}}

    - name: Build NuGet package
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: dotnet pack .\source\OpenMagic\OpenMagic.csproj --output .\artifacts

    - name: Publish NuGet package
      working-directory: ${{env.GITHUB_WORKSPACE}}
      env:
        MYGET_API_KEY: ${{secrets.MYGET_API_KEY}}
      if: github.ref == 'refs/heads/master'
      run: dotnet nuget push .\artifacts\${{env.PROJECT_NAME}}.${{env.VERSION}}.nupkg --api-key ${{env.MYGET_API_KEY}} --source ${{env.NUGET_SERVER}}
