name: MSBuild

on:
  push:
    # branches: [ $default-branch ]
  pull_request:
    # branches: [ $default-branch ]

env:
  SOLUTION_FILE_PATH: .\OpenMagic.sln
  BUILD_CONFIGURATION: Release
  BUILD_VERBOSITY: Minimal
  BUILD_TARGET: ReBuild
  
# todo: what is this?
#permissions:
#  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out the source code
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /maxCpuCount /p:Configuration=${{env.BUILD_CONFIGURATION}} /verbosity:${{env.BUILD_VERBOSITY}} /target:${{env.BUILD_TARGET}} ${{env.SOLUTION_FILE_PATH}} 
